# Generated by Django 4.0.1 on 2022-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileupload',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
