# Generated by Django 4.0.1 on 2022-06-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_alter_datafileupload_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
